default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e_contracts
  username: postgres  # Usa l'username appropriato per il tuo database
  password: 15122004  # Specifica la password qui se non utilizzi variabili d'ambiente
  host: localhost  # Assicurati di specificare l'host se necessario

test:
  <<: *default
  database: e_contracts
  username: postgres  # Stesso username se necessario
  password: 15122004  # Specifica la password anche qui se necessario

production:
  <<: *default
  database: e_contracts
  username: postgres
  password: <%= ENV["E_CONTRACT_BACK_DATABASE_PASSWORD"] %>
